import "~/styles/globals.css"

import {Inter} from "next/font/google"

// FONTS ***********************************************************************************************************************************
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

// METADATA ********************************************************************************************************************************
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{rel: "icon", url: "/favicon.ico"}],
}

// MAIN ************************************************************************************************************************************
export default function RootLayout({children}: Props) {
  return (
    <html lang="fr">
      <body className={`font-sans ${inter.variable}`}>{children}</body>
    </html>
  )
}

// TYPES ***********************************************************************************************************************************
interface Props {
  children: React.ReactNode
}